### ISSUE TITLE
senaica_param_data: Lexical Error

### ISSUE THREAD

**Issue by juancarlosyanes1** [diegovalle/rsinaica#5]
Hi,

Thanks for the great tool.

When using senaica_param_data I get the following error: 

```
> df <- sinaica_param_data("O3", "2015-10-14", "2015-10-14")
Error: lexical error: invalid char in json text.
                                       <br /> <b>Warning</b>:  file_ge
                     (right here) ------^
```

Wondering how I can solve this, thank you in advance.

**Comment by diegovalle** [comment]
Hi, sometimes the SINAICA website returns an error, as a workaround you could try:

1) Uing the API, for example https://api.datos.gob.mx/v2/sinaica?pageSize=5000&parametro=O3&page=1, but I'm not sure it's being update anymore
2) Try looping through the stations you need data from by using the `sinaica_station_data`  function 
```
sinaica_station_data(271, "O3", "2015-09-11", "2015-09-11", "Crude")
```
